[package]
name = "types"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.5.5", features = ["derive"] }
ed25519-dalek = "2"
curve25519-dalek = "4"
sha2 = "0.10"
sha3 = "0.10"
aes-gcm = "0.10.3"
solana-sha256-hasher = "2.2.1"
